server {
	listen 80;
	server_name _;

	root /usr/share/nginx/html;
	index index.html;

	# SPA: любой неизвестный путь отдаём index.html, роутинг разрулит react-router.
	location / {
		try_files $uri $uri/ /index.html;
	}
}
